name: Script Test

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: 'Version'
        required: true
        default: 'ZYB'

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Exec script
        uses: actions/github-script@v4
        id: set-result
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const compare = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: `${context.repo.owner}:dev`,
              head: `${context.repo.owner}:hasdiff`
            });

            console.log(compare);

      - name: Finish
        run: |
          echo "All steps finished"
