name: Script Test

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: 'Version'
        required: true
        default: 'ZYB'

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Exec script
        uses: actions/github-script@v4
        id: set-result
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diverged = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: `${context.repo.owner}:dev`,
              head: `${context.repo.owner}:hasdiff`
            });

            const behind = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: `${context.repo.owner}:dev`,
              head: `${context.repo.owner}:nodiff`
            });

            const ahead = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: `${context.repo.owner}:dev`,
              head: `${context.repo.owner}:ahead`
            });

            console.log(`diverged status = ${diverged.data.status}`);
            console.log(`behind status = ${behind.data.status}`);
            console.log(`ahead status = ${ahead.data.status}`);

      - name: Finish
        run: |
          echo "All steps finished"
