name: Script Test

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: 'Version'
        required: true
        default: 'ZYB'

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Exec script
        uses: actions/github-script@v4
        id: set-result
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const listPR = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "all",
              head: "script-dev"
            });
            console.log(listPR);
            return listPR;

      # - name: Pint result
      #   run: |
      #     echo ${{steps.set-result.outputs.result}}

      - name: Finish
        run: |
          echo "All steps finished"
