name: Dispatch Test

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: 'Name'
        required: true
        default: 'ZYB'
      home:
        description: 'Location'
        required: false
        default: 'Tokyo'

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Print Infomation
        run: |
          echo "name: ${{github.event.inputs.name}}"
          echo "location: ${{github.event.inputs.home}}"

      - name: Finish
        run: |
          echo "All steps finished"
